var ctx = oEvent.getSource().getBindingContext();
var data = JSON.parse(JSON.stringify(ctx.getObject()));
modeloInvoiceDetailModel.setData(data);
oInvoiceIdText.setText(data.invoiceId);
oInvoicePOText.setText(data.poNumber);
oInvoiceEntityText.setText(data.entity || "");
oInvoiceStatusText.setText(data.status);
oInvoiceDateText.setText(data.invoiceDate || "");
oInvoiceDueDateText.setText(data.dueDate || "");
oInvoiceGrossText.setText(String(data.grossAmount));
oInvoiceAdvanceText.setText(String(data.advanceAmount));
oInvoiceNetText.setText(String(data.netPayable));
oInvoiceRejectionText.setText(data.rejectionReason || "");
oInvoiceRejectionText.setVisible(!!data.rejectionReason);
modeloLineItemsTable.setData(data.lineItems || []);
modeloAttachmentsList.setData(data.attachments || []);
var canDecide = (data.status === "Submitted" || data.status === "Under Review");
oApproveBtn.setVisible(canDecide);
oRejectBtn.setVisible(canDecide);
oNavContainer.to(oInvoiceDetailPage);
oLineItemsTable.bindItems({ path: "/", template: liLineItem });
oAttachmentsList.bindItems({ path: "/", template: liAttachment });